# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseInfo',
            new_name='UserInfo',
        ),
    ]
