# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190228_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
