# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 02:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190228_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
