# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190228_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth',
        ),
    ]
