# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
