# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-30 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QQ', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
